"""Pure-Python calculation engine — Excel-exact Marshall mix design."""

from .interpolation import linear_interpolate, bracket_interpolate
from .gradation import GradationInput, GradationResult, compute_gradation
from .specific_gravity import (
    CoarseAggSGInput,
    FineAggSGInput,
    BitumenSGInput,
    SpecificGravityResult,
    compute_coarse_sg,
    compute_fine_sg,
    compute_bitumen_sg,
    compute_bulk_sg_blend,
)
from .gmb import GmbSpecimen, GmbGroup, GmbInput, GmbResult, compute_gmb
from .gmm import GmmSampleRaw, GmmInput, GmmResult, compute_gmm
from .stability_flow import (
    StabilitySpecimen,
    StabilityFlowInput,
    StabilityFlowResult,
    compute_stability_flow,
)
from .marshall import MarshallSummary, MarshallRow, build_marshall_summary
from .obc import compute_obc, properties_at_obc, OBCResult
from .compliance import (
    MixSpec,
    MixTypeRecord,
    ComplianceResult,
    check_compliance,
    reload_specs,
    save_specs,
    MIX_SPECS,
    MIX_TYPES,
)
from .models import MixDesignInput, MixDesignResult, compute_mix_design
from .material_calc import (
    MaterialCalcInput,
    MaterialBlock,
    DryMaterialRow,
    MaterialCalcResult,
    compute_material_calc,
)
from .import_summary import ImportedMixResult, parse_summary_excel
from .binders import BinderGrade, BINDER_GRADES, PROPERTY_LABELS, load_binders, reload_binders
from .code_refs import CodeRef, CodeRecord, CODE_REGISTRY, get_code, parse_refs, labels as code_labels
from .material_quantity import (
    LayerInput,
    LayerResult,
    MaterialQuantityInput,
    MaterialQuantityResult,
    LAYER_TYPES,
    compute_layer,
    compute_material_quantity,
)
from .structural_design import (
    StructuralInput,
    PavementLayer,
    StructuralResult,
    compute_design_traffic,
    compute_subgrade_mr,
    suggest_composition,
    compute_structural_design,
)
from .maintenance import (
    OverlayInput,
    OverlayResult,
    compute_overlay,
    characteristic_deflection,
    allowable_deflection,
    temperature_corrected_deflection,
    ColdMixInput,
    ColdMixResult,
    compute_cold_mix,
    MicroSurfacingInput,
    MicroSurfacingResult,
    compute_micro_surfacing,
)

__all__ = [
    "linear_interpolate",
    "bracket_interpolate",
    "GradationInput",
    "GradationResult",
    "compute_gradation",
    "CoarseAggSGInput",
    "FineAggSGInput",
    "BitumenSGInput",
    "SpecificGravityResult",
    "compute_coarse_sg",
    "compute_fine_sg",
    "compute_bitumen_sg",
    "compute_bulk_sg_blend",
    "GmbSpecimen",
    "GmbGroup",
    "GmbInput",
    "GmbResult",
    "compute_gmb",
    "GmmSampleRaw",
    "GmmInput",
    "GmmResult",
    "compute_gmm",
    "StabilitySpecimen",
    "StabilityFlowInput",
    "StabilityFlowResult",
    "compute_stability_flow",
    "MarshallSummary",
    "MarshallRow",
    "build_marshall_summary",
    "compute_obc",
    "properties_at_obc",
    "OBCResult",
    "MixSpec",
    "MixTypeRecord",
    "ComplianceResult",
    "check_compliance",
    "reload_specs",
    "save_specs",
    "MIX_SPECS",
    "MIX_TYPES",
    "MixDesignInput",
    "MixDesignResult",
    "compute_mix_design",
    "MaterialCalcInput",
    "MaterialBlock",
    "DryMaterialRow",
    "MaterialCalcResult",
    "compute_material_calc",
    "ImportedMixResult",
    "parse_summary_excel",
    "BinderGrade",
    "BINDER_GRADES",
    "PROPERTY_LABELS",
    "load_binders",
    "reload_binders",
    "StructuralInput",
    "PavementLayer",
    "StructuralResult",
    "compute_design_traffic",
    "compute_subgrade_mr",
    "suggest_composition",
    "compute_structural_design",
    "OverlayInput",
    "OverlayResult",
    "compute_overlay",
    "characteristic_deflection",
    "allowable_deflection",
    "temperature_corrected_deflection",
    "ColdMixInput",
    "ColdMixResult",
    "compute_cold_mix",
    "MicroSurfacingInput",
    "MicroSurfacingResult",
    "compute_micro_surfacing",
    "CodeRef",
    "CodeRecord",
    "CODE_REGISTRY",
    "get_code",
    "parse_refs",
    "code_labels",
    "LayerInput",
    "LayerResult",
    "MaterialQuantityInput",
    "MaterialQuantityResult",
    "LAYER_TYPES",
    "compute_layer",
    "compute_material_quantity",
]
