"""Pure-Python calculation engine — Excel-exact Marshall mix design."""

from .interpolation import linear_interpolate, bracket_interpolate
from .gradation import GradationInput, GradationResult, compute_gradation
from .specific_gravity import (
    CoarseAggSGInput,
    FineAggSGInput,
    BitumenSGInput,
    SpecificGravityResult,
    compute_coarse_sg,
    compute_fine_sg,
    compute_bitumen_sg,
    compute_bulk_sg_blend,
)
from .gmb import GmbSpecimen, GmbGroup, GmbInput, GmbResult, compute_gmb
from .gmm import GmmSampleRaw, GmmInput, GmmResult, compute_gmm
from .stability_flow import (
    StabilitySpecimen,
    StabilityFlowInput,
    StabilityFlowResult,
    compute_stability_flow,
)
from .marshall import MarshallSummary, MarshallRow, build_marshall_summary
from .obc import compute_obc, properties_at_obc, OBCResult, spec_target_air_voids
from .compliance import (
    MixSpec,
    MixTypeRecord,
    ComplianceResult,
    check_compliance,
    reload_specs,
    save_specs,
    MIX_SPECS,
    MIX_TYPES,
)
from .models import MixDesignInput, MixDesignResult, compute_mix_design
from .material_calc import (
    MaterialCalcInput,
    MaterialBlock,
    DryMaterialRow,
    MaterialCalcResult,
    compute_material_calc,
)
from .import_summary import ImportedMixResult, parse_summary_excel
from .binders import BinderGrade, BINDER_GRADES, PROPERTY_LABELS, load_binders, reload_binders
from .code_refs import CodeRef, CodeRecord, CODE_REGISTRY, get_code, parse_refs, labels as code_labels
from .material_quantity import (
    LayerInput,
    LayerResult,
    MaterialQuantityInput,
    MaterialQuantityResult,
    LAYER_TYPES,
    compute_layer,
    compute_material_quantity,
)
from .traffic import (
    TrafficInput,
    TrafficResult,
    TERRAINS,
    LANE_CONFIGS,
    vdf_preset,
    ldf_preset,
    traffic_category,
    compute_traffic_analysis,
)
from .structural_design import (
    StructuralInput,
    PavementLayer,
    StructuralResult,
    compute_design_traffic,
    compute_subgrade_mr,
    suggest_composition,
    compute_structural_design,
)
from .maintenance import (
    OverlayInput,
    OverlayResult,
    compute_overlay,
    characteristic_deflection,
    allowable_deflection,
    temperature_corrected_deflection,
    ColdMixInput,
    ColdMixResult,
    compute_cold_mix,
    MicroSurfacingInput,
    MicroSurfacingResult,
    compute_micro_surfacing,
)
from .condition_survey import (
    DISTRESS_TYPES,
    SEVERITY_LEVELS,
    DistressType,
    DistressRecord,
    ConditionSurveyInput,
    ConditionSurveyResult,
    PerDistressBreakdown,
    RehabRecommendation,
    PCICalibration,
    DEFAULT_CALIBRATION as PCI_DEFAULT_CALIBRATION,
    get_calibration as get_pci_calibration,
    set_calibration as set_pci_calibration,
    reset_calibration as reset_pci_calibration,
    compute_condition_survey,
    condition_category,
    recommend_rehab,
    RECALIBRATE_ME as PCI_RECALIBRATE_ME,
    PLACEHOLDER_NOTE as PCI_PLACEHOLDER_NOTE,
)

__all__ = [
    "linear_interpolate",
    "bracket_interpolate",
    "GradationInput",
    "GradationResult",
    "compute_gradation",
    "CoarseAggSGInput",
    "FineAggSGInput",
    "BitumenSGInput",
    "SpecificGravityResult",
    "compute_coarse_sg",
    "compute_fine_sg",
    "compute_bitumen_sg",
    "compute_bulk_sg_blend",
    "GmbSpecimen",
    "GmbGroup",
    "GmbInput",
    "GmbResult",
    "compute_gmb",
    "GmmSampleRaw",
    "GmmInput",
    "GmmResult",
    "compute_gmm",
    "StabilitySpecimen",
    "StabilityFlowInput",
    "StabilityFlowResult",
    "compute_stability_flow",
    "MarshallSummary",
    "MarshallRow",
    "build_marshall_summary",
    "compute_obc",
    "properties_at_obc",
    "OBCResult",
    "spec_target_air_voids",
    "MixSpec",
    "MixTypeRecord",
    "ComplianceResult",
    "check_compliance",
    "reload_specs",
    "save_specs",
    "MIX_SPECS",
    "MIX_TYPES",
    "MixDesignInput",
    "MixDesignResult",
    "compute_mix_design",
    "MaterialCalcInput",
    "MaterialBlock",
    "DryMaterialRow",
    "MaterialCalcResult",
    "compute_material_calc",
    "ImportedMixResult",
    "parse_summary_excel",
    "BinderGrade",
    "BINDER_GRADES",
    "PROPERTY_LABELS",
    "load_binders",
    "reload_binders",
    "StructuralInput",
    "PavementLayer",
    "StructuralResult",
    "compute_design_traffic",
    "compute_subgrade_mr",
    "suggest_composition",
    "compute_structural_design",
    "OverlayInput",
    "OverlayResult",
    "compute_overlay",
    "characteristic_deflection",
    "allowable_deflection",
    "temperature_corrected_deflection",
    "ColdMixInput",
    "ColdMixResult",
    "compute_cold_mix",
    "MicroSurfacingInput",
    "MicroSurfacingResult",
    "compute_micro_surfacing",
    "CodeRef",
    "CodeRecord",
    "CODE_REGISTRY",
    "get_code",
    "parse_refs",
    "code_labels",
    "LayerInput",
    "LayerResult",
    "MaterialQuantityInput",
    "MaterialQuantityResult",
    "LAYER_TYPES",
    "compute_layer",
    "compute_material_quantity",
    "TrafficInput",
    "TrafficResult",
    "TERRAINS",
    "LANE_CONFIGS",
    "vdf_preset",
    "ldf_preset",
    "traffic_category",
    "compute_traffic_analysis",
    "DISTRESS_TYPES",
    "SEVERITY_LEVELS",
    "DistressType",
    "DistressRecord",
    "ConditionSurveyInput",
    "ConditionSurveyResult",
    "PerDistressBreakdown",
    "RehabRecommendation",
    "PCICalibration",
    "PCI_DEFAULT_CALIBRATION",
    "get_pci_calibration",
    "set_pci_calibration",
    "reset_pci_calibration",
    "compute_condition_survey",
    "condition_category",
    "recommend_rehab",
    "PCI_RECALIBRATE_ME",
    "PCI_PLACEHOLDER_NOTE",
]
